# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tack-It' do
  # Pods for Tack-It
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
end
