# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tack-It' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tack-It
pod 'Firebase/Core'
  target 'Tack-ItTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Tack-ItUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
